DROP TABLE IF EXISTS blocks;
DROP TABLE IF EXISTS page_slugs;
DROP TABLE IF EXISTS pages;
DROP TABLE IF EXISTS blog_slugs;
DROP TABLE IF EXISTS blogs;
DROP TABLE IF EXISTS site_locales;
DROP TABLE IF EXISTS sites;
DROP TABLE IF EXISTS users;
