// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: blocks.sql

package db

import (
	"context"
)

const createBlockCounter = `-- name: CreateBlockCounter :one
INSERT INTO block_counters (site_id, current_value)
VALUES ($1, 2)
RETURNING site_id, current_value
`

func (q *Queries) CreateBlockCounter(ctx context.Context, siteID int64) (BlockCounter, error) {
	row := q.db.QueryRow(ctx, createBlockCounter, siteID)
	var i BlockCounter
	err := row.Scan(&i.SiteID, &i.CurrentValue)
	return i, err
}

const getNextBlockID = `-- name: GetNextBlockID :one
INSERT INTO block_counters (site_id, current_value)
VALUES ($1, 1)
ON CONFLICT (site_id) DO UPDATE
SET current_value = block_counters.current_value + 1
RETURNING current_value AS id
`

func (q *Queries) GetNextBlockID(ctx context.Context, siteID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getNextBlockID, siteID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
