// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locales.sql

package db

import (
	"context"
)

const createSiteLocale = `-- name: CreateSiteLocale :one
INSERT INTO site_locales (site_id, code, is_default)
VALUES ($1, $2, $3)
RETURNING id, site_id, code, is_default, created_at
`

type CreateSiteLocaleParams struct {
	SiteID    int64  `json:"site_id"`
	Code      string `json:"code"`
	IsDefault bool   `json:"is_default"`
}

func (q *Queries) CreateSiteLocale(ctx context.Context, arg CreateSiteLocaleParams) (SiteLocale, error) {
	row := q.db.QueryRow(ctx, createSiteLocale, arg.SiteID, arg.Code, arg.IsDefault)
	var i SiteLocale
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Code,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSiteLocale = `-- name: DeleteSiteLocale :exec
DELETE FROM site_locales WHERE id = $1 AND site_id = $2
`

type DeleteSiteLocaleParams struct {
	ID     int64 `json:"id"`
	SiteID int64 `json:"site_id"`
}

func (q *Queries) DeleteSiteLocale(ctx context.Context, arg DeleteSiteLocaleParams) error {
	_, err := q.db.Exec(ctx, deleteSiteLocale, arg.ID, arg.SiteID)
	return err
}

const deleteSiteLocaleByCode = `-- name: DeleteSiteLocaleByCode :exec
DELETE FROM site_locales WHERE code = $1 AND site_id = $2
`

type DeleteSiteLocaleByCodeParams struct {
	Code   string `json:"code"`
	SiteID int64  `json:"site_id"`
}

func (q *Queries) DeleteSiteLocaleByCode(ctx context.Context, arg DeleteSiteLocaleByCodeParams) error {
	_, err := q.db.Exec(ctx, deleteSiteLocaleByCode, arg.Code, arg.SiteID)
	return err
}

const getSiteLocaleByCodeAndSite = `-- name: GetSiteLocaleByCodeAndSite :one
SELECT id, site_id, code, is_default, created_at FROM site_locales WHERE code = $1 AND site_id = $2
`

type GetSiteLocaleByCodeAndSiteParams struct {
	Code   string `json:"code"`
	SiteID int64  `json:"site_id"`
}

func (q *Queries) GetSiteLocaleByCodeAndSite(ctx context.Context, arg GetSiteLocaleByCodeAndSiteParams) (SiteLocale, error) {
	row := q.db.QueryRow(ctx, getSiteLocaleByCodeAndSite, arg.Code, arg.SiteID)
	var i SiteLocale
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Code,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteLocaleByID = `-- name: GetSiteLocaleByID :one
SELECT id, site_id, code, is_default, created_at FROM site_locales WHERE id = $1
`

func (q *Queries) GetSiteLocaleByID(ctx context.Context, id int64) (SiteLocale, error) {
	row := q.db.QueryRow(ctx, getSiteLocaleByID, id)
	var i SiteLocale
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Code,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const listSiteLocales = `-- name: ListSiteLocales :many
SELECT id, site_id, code, is_default, created_at
FROM site_locales
WHERE site_id = $1
ORDER BY is_default DESC, code ASC
`

func (q *Queries) ListSiteLocales(ctx context.Context, siteID int64) ([]SiteLocale, error) {
	rows, err := q.db.Query(ctx, listSiteLocales, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteLocale
	for rows.Next() {
		var i SiteLocale
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Code,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteLocalesBySiteIDs = `-- name: ListSiteLocalesBySiteIDs :many
SELECT id, site_id, code, is_default, created_at
FROM site_locales
WHERE site_id = ANY($1::BIGINT[])
ORDER BY is_default DESC, code ASC
`

func (q *Queries) ListSiteLocalesBySiteIDs(ctx context.Context, dollar_1 []int64) ([]SiteLocale, error) {
	rows, err := q.db.Query(ctx, listSiteLocalesBySiteIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteLocale
	for rows.Next() {
		var i SiteLocale
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Code,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsetDefaultLocales = `-- name: UnsetDefaultLocales :exec
UPDATE site_locales SET is_default = false WHERE site_id = $1 AND is_default = true
`

func (q *Queries) UnsetDefaultLocales(ctx context.Context, siteID int64) error {
	_, err := q.db.Exec(ctx, unsetDefaultLocales, siteID)
	return err
}
