// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: media.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMedia = `-- name: CountMedia :one
SELECT COUNT(*) FROM media
`

func (q *Queries) CountMedia(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMedia)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (filename, mime_type, size, url, thumbnail_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, filename, mime_type, size, url, thumbnail_url, created_at
`

type CreateMediaParams struct {
	Filename     string      `json:"filename"`
	MimeType     string      `json:"mime_type"`
	Size         int64       `json:"size"`
	Url          string      `json:"url"`
	ThumbnailUrl pgtype.Text `json:"thumbnail_url"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.Filename,
		arg.MimeType,
		arg.Size,
		arg.Url,
		arg.ThumbnailUrl,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.MimeType,
		&i.Size,
		&i.Url,
		&i.ThumbnailUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :one
DELETE FROM media
WHERE id = $1
RETURNING id, filename, mime_type, size, url, thumbnail_url, created_at
`

func (q *Queries) DeleteMedia(ctx context.Context, id int64) (Medium, error) {
	row := q.db.QueryRow(ctx, deleteMedia, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.MimeType,
		&i.Size,
		&i.Url,
		&i.ThumbnailUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, filename, mime_type, size, url, thumbnail_url, created_at FROM media
WHERE id = $1
`

func (q *Queries) GetMediaByID(ctx context.Context, id int64) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.MimeType,
		&i.Size,
		&i.Url,
		&i.ThumbnailUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listMedia = `-- name: ListMedia :many
SELECT id, filename, mime_type, size, url, thumbnail_url, created_at FROM media
WHERE ($1::BIGINT IS NULL OR id > $1)
ORDER BY id ASC
LIMIT $2
`

type ListMediaParams struct {
	Column1 int64 `json:"column_1"`
	Limit   int32 `json:"limit"`
}

func (q *Queries) ListMedia(ctx context.Context, arg ListMediaParams) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMedia, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.MimeType,
			&i.Size,
			&i.Url,
			&i.ThumbnailUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
