// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BlockCounter struct {
	SiteID       int64 `json:"site_id"`
	CurrentValue int64 `json:"current_value"`
}

type Blog struct {
	ID        int64              `json:"id"`
	SiteID    int64              `json:"site_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type BlogSlug struct {
	ID       int64  `json:"id"`
	BlogID   int64  `json:"blog_id"`
	LocaleID int64  `json:"locale_id"`
	Slug     string `json:"slug"`
}

type Medium struct {
	ID           int64              `json:"id"`
	Filename     string             `json:"filename"`
	MimeType     string             `json:"mime_type"`
	Size         int64              `json:"size"`
	Url          string             `json:"url"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Page struct {
	ID          int64              `json:"id"`
	SiteID      int64              `json:"site_id"`
	BlogID      pgtype.Int8        `json:"blog_id"`
	ParentID    pgtype.Int8        `json:"parent_id"`
	Type        string             `json:"type"`
	Layout      []byte             `json:"layout"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PageRender struct {
	ID        int64              `json:"id"`
	PageID    int64              `json:"page_id"`
	LocaleID  int64              `json:"locale_id"`
	Html      string             `json:"html"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PageRevision struct {
	ID             int64              `json:"id"`
	PageID         int64              `json:"page_id"`
	Layout         []byte             `json:"layout"`
	RevisionNumber int32              `json:"revision_number"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PageSeo struct {
	ID          int64              `json:"id"`
	PageID      int64              `json:"page_id"`
	LocaleID    int64              `json:"locale_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PageSlug struct {
	ID       int64  `json:"id"`
	PageID   int64  `json:"page_id"`
	LocaleID int64  `json:"locale_id"`
	Slug     string `json:"slug"`
}

type SectionCounter struct {
	SiteID       int64 `json:"site_id"`
	CurrentValue int64 `json:"current_value"`
}

type Site struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Domain    string             `json:"domain"`
	Options   []byte             `json:"options"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	IsLive    bool               `json:"is_live"`
}

type SiteLocale struct {
	ID        int64              `json:"id"`
	SiteID    int64              `json:"site_id"`
	Code      string             `json:"code"`
	IsDefault bool               `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
