// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: page_renders.sql

package db

import (
	"context"
)

const deletePageRendersByPageID = `-- name: DeletePageRendersByPageID :exec
DELETE FROM page_renders WHERE page_id = $1
`

func (q *Queries) DeletePageRendersByPageID(ctx context.Context, pageID int64) error {
	_, err := q.db.Exec(ctx, deletePageRendersByPageID, pageID)
	return err
}

const getAllPublishedPageIDs = `-- name: GetAllPublishedPageIDs :many
SELECT DISTINCT p.id FROM pages p WHERE p.site_id = $1 AND p.published_at IS NOT NULL
`

func (q *Queries) GetAllPublishedPageIDs(ctx context.Context, siteID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getAllPublishedPageIDs, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPageRenderByPageAndLocale = `-- name: GetPageRenderByPageAndLocale :one
SELECT id, page_id, locale_id, html, updated_at
FROM page_renders
WHERE page_id = $1 AND locale_id = $2
`

type GetPageRenderByPageAndLocaleParams struct {
	PageID   int64 `json:"page_id"`
	LocaleID int64 `json:"locale_id"`
}

func (q *Queries) GetPageRenderByPageAndLocale(ctx context.Context, arg GetPageRenderByPageAndLocaleParams) (PageRender, error) {
	row := q.db.QueryRow(ctx, getPageRenderByPageAndLocale, arg.PageID, arg.LocaleID)
	var i PageRender
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.LocaleID,
		&i.Html,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedPageSlug = `-- name: GetPublishedPageSlug :one
SELECT ps.page_id, sl.id AS locale_id, sl.code AS locale_code, sl.is_default
FROM page_slugs ps
JOIN site_locales sl ON sl.id = ps.locale_id
JOIN pages p ON p.id = ps.page_id
WHERE p.site_id = $1 AND ps.slug = $2 AND sl.code = $3 AND p.published_at IS NOT NULL
`

type GetPublishedPageSlugParams struct {
	SiteID int64  `json:"site_id"`
	Slug   string `json:"slug"`
	Code   string `json:"code"`
}

type GetPublishedPageSlugRow struct {
	PageID     int64  `json:"page_id"`
	LocaleID   int64  `json:"locale_id"`
	LocaleCode string `json:"locale_code"`
	IsDefault  bool   `json:"is_default"`
}

func (q *Queries) GetPublishedPageSlug(ctx context.Context, arg GetPublishedPageSlugParams) (GetPublishedPageSlugRow, error) {
	row := q.db.QueryRow(ctx, getPublishedPageSlug, arg.SiteID, arg.Slug, arg.Code)
	var i GetPublishedPageSlugRow
	err := row.Scan(
		&i.PageID,
		&i.LocaleID,
		&i.LocaleCode,
		&i.IsDefault,
	)
	return i, err
}

const upsertPageRender = `-- name: UpsertPageRender :one
INSERT INTO page_renders (page_id, locale_id, html, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (page_id, locale_id)
DO UPDATE SET html = EXCLUDED.html, updated_at = NOW()
RETURNING id, page_id, locale_id, html, updated_at
`

type UpsertPageRenderParams struct {
	PageID   int64  `json:"page_id"`
	LocaleID int64  `json:"locale_id"`
	Html     string `json:"html"`
}

func (q *Queries) UpsertPageRender(ctx context.Context, arg UpsertPageRenderParams) (PageRender, error) {
	row := q.db.QueryRow(ctx, upsertPageRender, arg.PageID, arg.LocaleID, arg.Html)
	var i PageRender
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.LocaleID,
		&i.Html,
		&i.UpdatedAt,
	)
	return i, err
}
