// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPage = `-- name: CreatePage :one
INSERT INTO pages (site_id, blog_id, parent_id, type, layout, published_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, site_id, blog_id, parent_id, type, layout, published_at, created_at, updated_at
`

type CreatePageParams struct {
	SiteID      int64              `json:"site_id"`
	BlogID      pgtype.Int8        `json:"blog_id"`
	ParentID    pgtype.Int8        `json:"parent_id"`
	Type        string             `json:"type"`
	Layout      []byte             `json:"layout"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, createPage,
		arg.SiteID,
		arg.BlogID,
		arg.ParentID,
		arg.Type,
		arg.Layout,
		arg.PublishedAt,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.BlogID,
		&i.ParentID,
		&i.Type,
		&i.Layout,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPageSeo = `-- name: CreatePageSeo :one
INSERT INTO page_seo (page_id, locale_id, title, description)
VALUES ($1, $2, $3, $4)
RETURNING id, page_id, locale_id, title, description
`

type CreatePageSeoParams struct {
	PageID      int64       `json:"page_id"`
	LocaleID    int64       `json:"locale_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
}

type CreatePageSeoRow struct {
	ID          int64       `json:"id"`
	PageID      int64       `json:"page_id"`
	LocaleID    int64       `json:"locale_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreatePageSeo(ctx context.Context, arg CreatePageSeoParams) (CreatePageSeoRow, error) {
	row := q.db.QueryRow(ctx, createPageSeo,
		arg.PageID,
		arg.LocaleID,
		arg.Title,
		arg.Description,
	)
	var i CreatePageSeoRow
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.LocaleID,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const createPageSlug = `-- name: CreatePageSlug :one
INSERT INTO page_slugs (page_id, locale_id, slug)
VALUES ($1, $2, $3)
RETURNING id, page_id, locale_id, slug
`

type CreatePageSlugParams struct {
	PageID   int64  `json:"page_id"`
	LocaleID int64  `json:"locale_id"`
	Slug     string `json:"slug"`
}

func (q *Queries) CreatePageSlug(ctx context.Context, arg CreatePageSlugParams) (PageSlug, error) {
	row := q.db.QueryRow(ctx, createPageSlug, arg.PageID, arg.LocaleID, arg.Slug)
	var i PageSlug
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.LocaleID,
		&i.Slug,
	)
	return i, err
}

const deletePage = `-- name: DeletePage :one
DELETE FROM pages WHERE id = $1 AND site_id = $2 RETURNING id
`

type DeletePageParams struct {
	ID     int64 `json:"id"`
	SiteID int64 `json:"site_id"`
}

func (q *Queries) DeletePage(ctx context.Context, arg DeletePageParams) (int64, error) {
	row := q.db.QueryRow(ctx, deletePage, arg.ID, arg.SiteID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deletePageSeoByPageID = `-- name: DeletePageSeoByPageID :exec
DELETE FROM page_seo WHERE page_id = $1
`

func (q *Queries) DeletePageSeoByPageID(ctx context.Context, pageID int64) error {
	_, err := q.db.Exec(ctx, deletePageSeoByPageID, pageID)
	return err
}

const deletePageSlugsByPageID = `-- name: DeletePageSlugsByPageID :exec
DELETE FROM page_slugs WHERE page_id = $1
`

func (q *Queries) DeletePageSlugsByPageID(ctx context.Context, pageID int64) error {
	_, err := q.db.Exec(ctx, deletePageSlugsByPageID, pageID)
	return err
}

const getBlogByID = `-- name: GetBlogByID :one
SELECT id, site_id, created_at, updated_at
FROM blogs
WHERE id = $1 AND site_id = $2
`

type GetBlogByIDParams struct {
	ID     int64 `json:"id"`
	SiteID int64 `json:"site_id"`
}

func (q *Queries) GetBlogByID(ctx context.Context, arg GetBlogByIDParams) (Blog, error) {
	row := q.db.QueryRow(ctx, getBlogByID, arg.ID, arg.SiteID)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBlogRoutes = `-- name: GetBlogRoutes :many
SELECT b.id AS blog_id, sl.code AS locale_code, sl.is_default, bs.slug AS path
FROM blogs b
JOIN blog_slugs bs ON bs.blog_id = b.id
JOIN site_locales sl ON sl.id = bs.locale_id
WHERE b.site_id = $1
ORDER BY bs.slug
`

type GetBlogRoutesRow struct {
	BlogID     int64  `json:"blog_id"`
	LocaleCode string `json:"locale_code"`
	IsDefault  bool   `json:"is_default"`
	Path       string `json:"path"`
}

func (q *Queries) GetBlogRoutes(ctx context.Context, siteID int64) ([]GetBlogRoutesRow, error) {
	rows, err := q.db.Query(ctx, getBlogRoutes, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBlogRoutesRow
	for rows.Next() {
		var i GetBlogRoutesRow
		if err := rows.Scan(
			&i.BlogID,
			&i.LocaleCode,
			&i.IsDefault,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPageByID = `-- name: GetPageByID :one
SELECT id, site_id, blog_id, parent_id, type, layout, published_at, created_at, updated_at
FROM pages
WHERE id = $1 AND site_id = $2
`

type GetPageByIDParams struct {
	ID     int64 `json:"id"`
	SiteID int64 `json:"site_id"`
}

func (q *Queries) GetPageByID(ctx context.Context, arg GetPageByIDParams) (Page, error) {
	row := q.db.QueryRow(ctx, getPageByID, arg.ID, arg.SiteID)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.BlogID,
		&i.ParentID,
		&i.Type,
		&i.Layout,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageRoutes = `-- name: GetPageRoutes :many
WITH RECURSIVE page_tree AS (
    SELECT p.id, ps.locale_id, sl.code, sl.is_default, ps.slug::TEXT AS path
    FROM pages p
    JOIN page_slugs ps ON ps.page_id = p.id
    JOIN site_locales sl ON sl.id = ps.locale_id
    WHERE p.site_id = $1 AND p.type = 'page' AND p.parent_id IS NULL
      AND p.published_at IS NOT NULL
  UNION ALL
    SELECT c.id, cs.locale_id, sl.code, sl.is_default,
           CASE WHEN pt.path = '' THEN cs.slug ELSE pt.path || '/' || cs.slug END
    FROM pages c
    JOIN page_slugs cs ON cs.page_id = c.id
    JOIN site_locales sl ON sl.id = cs.locale_id
    JOIN page_tree pt ON pt.id = c.parent_id AND pt.locale_id = cs.locale_id
    WHERE c.site_id = $1 AND c.type = 'page' AND c.published_at IS NOT NULL
)
SELECT id AS page_id, locale_id, code AS locale_code, is_default, path
FROM page_tree ORDER BY path
`

type GetPageRoutesRow struct {
	PageID     int64  `json:"page_id"`
	LocaleID   int64  `json:"locale_id"`
	LocaleCode string `json:"locale_code"`
	IsDefault  bool   `json:"is_default"`
	Path       string `json:"path"`
}

func (q *Queries) GetPageRoutes(ctx context.Context, siteID int64) ([]GetPageRoutesRow, error) {
	rows, err := q.db.Query(ctx, getPageRoutes, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPageRoutesRow
	for rows.Next() {
		var i GetPageRoutesRow
		if err := rows.Scan(
			&i.PageID,
			&i.LocaleID,
			&i.LocaleCode,
			&i.IsDefault,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPageSeoByPageID = `-- name: GetPageSeoByPageID :many
SELECT id, page_id, locale_id, title, description
FROM page_seo
WHERE page_id = $1
`

type GetPageSeoByPageIDRow struct {
	ID          int64       `json:"id"`
	PageID      int64       `json:"page_id"`
	LocaleID    int64       `json:"locale_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) GetPageSeoByPageID(ctx context.Context, pageID int64) ([]GetPageSeoByPageIDRow, error) {
	rows, err := q.db.Query(ctx, getPageSeoByPageID, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPageSeoByPageIDRow
	for rows.Next() {
		var i GetPageSeoByPageIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.LocaleID,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPageSeoByPageIDs = `-- name: GetPageSeoByPageIDs :many
SELECT id, page_id, locale_id, title, description
FROM page_seo
WHERE page_id = ANY($1::BIGINT[])
`

type GetPageSeoByPageIDsRow struct {
	ID          int64       `json:"id"`
	PageID      int64       `json:"page_id"`
	LocaleID    int64       `json:"locale_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) GetPageSeoByPageIDs(ctx context.Context, dollar_1 []int64) ([]GetPageSeoByPageIDsRow, error) {
	rows, err := q.db.Query(ctx, getPageSeoByPageIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPageSeoByPageIDsRow
	for rows.Next() {
		var i GetPageSeoByPageIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.LocaleID,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPageSlugsByPageID = `-- name: GetPageSlugsByPageID :many
SELECT id, page_id, locale_id, slug
FROM page_slugs
WHERE page_id = $1
`

func (q *Queries) GetPageSlugsByPageID(ctx context.Context, pageID int64) ([]PageSlug, error) {
	rows, err := q.db.Query(ctx, getPageSlugsByPageID, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageSlug
	for rows.Next() {
		var i PageSlug
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.LocaleID,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPageSlugsByPageIDs = `-- name: GetPageSlugsByPageIDs :many
SELECT id, page_id, locale_id, slug
FROM page_slugs
WHERE page_id = ANY($1::BIGINT[])
`

func (q *Queries) GetPageSlugsByPageIDs(ctx context.Context, dollar_1 []int64) ([]PageSlug, error) {
	rows, err := q.db.Query(ctx, getPageSlugsByPageIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageSlug
	for rows.Next() {
		var i PageSlug
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.LocaleID,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostRoutes = `-- name: GetPostRoutes :many
WITH RECURSIVE post_tree AS (
    SELECT p.id, p.blog_id, ps.locale_id, ps.slug::TEXT AS path
    FROM pages p
    JOIN page_slugs ps ON ps.page_id = p.id
    WHERE p.site_id = $1 AND p.type = 'post' AND p.parent_id IS NULL
      AND p.published_at IS NOT NULL
  UNION ALL
    SELECT c.id, c.blog_id, cs.locale_id,
           CASE WHEN pt.path = '' THEN cs.slug ELSE pt.path || '/' || cs.slug END
    FROM pages c
    JOIN page_slugs cs ON cs.page_id = c.id
    JOIN post_tree pt ON pt.id = c.parent_id AND pt.locale_id = cs.locale_id
    WHERE c.site_id = $1 AND c.type = 'post' AND c.published_at IS NOT NULL
)
SELECT pt.id AS page_id, pt.blog_id, pt.locale_id, sl.code AS locale_code, sl.is_default,
       CASE WHEN pt.path = '' THEN bs.slug ELSE (bs.slug || '/' || pt.path)::TEXT END AS path
FROM post_tree pt
JOIN blog_slugs bs ON bs.blog_id = pt.blog_id AND bs.locale_id = pt.locale_id
JOIN site_locales sl ON sl.id = pt.locale_id
ORDER BY path
`

type GetPostRoutesRow struct {
	PageID     int64       `json:"page_id"`
	BlogID     pgtype.Int8 `json:"blog_id"`
	LocaleID   int64       `json:"locale_id"`
	LocaleCode string      `json:"locale_code"`
	IsDefault  bool        `json:"is_default"`
	Path       string      `json:"path"`
}

func (q *Queries) GetPostRoutes(ctx context.Context, siteID int64) ([]GetPostRoutesRow, error) {
	rows, err := q.db.Query(ctx, getPostRoutes, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostRoutesRow
	for rows.Next() {
		var i GetPostRoutesRow
		if err := rows.Scan(
			&i.PageID,
			&i.BlogID,
			&i.LocaleID,
			&i.LocaleCode,
			&i.IsDefault,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRootPageBySite = `-- name: GetRootPageBySite :one
SELECT p.id, p.site_id, p.blog_id, p.parent_id, p.type, p.layout, p.published_at, p.created_at, p.updated_at
FROM pages p
JOIN page_slugs ps ON ps.page_id = p.id
JOIN site_locales sl ON sl.id = ps.locale_id
WHERE p.site_id = $1 AND p.type = 'page' AND p.parent_id IS NULL
  AND sl.is_default = true AND ps.slug = ''
LIMIT 1
`

func (q *Queries) GetRootPageBySite(ctx context.Context, siteID int64) (Page, error) {
	row := q.db.QueryRow(ctx, getRootPageBySite, siteID)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.BlogID,
		&i.ParentID,
		&i.Type,
		&i.Layout,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePage = `-- name: UpdatePage :one
UPDATE pages
SET parent_id = $1, layout = $2, published_at = $3, updated_at = NOW()
WHERE id = $4 AND site_id = $5
RETURNING id, site_id, blog_id, parent_id, type, layout, published_at, created_at, updated_at
`

type UpdatePageParams struct {
	ParentID    pgtype.Int8        `json:"parent_id"`
	Layout      []byte             `json:"layout"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	ID          int64              `json:"id"`
	SiteID      int64              `json:"site_id"`
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, updatePage,
		arg.ParentID,
		arg.Layout,
		arg.PublishedAt,
		arg.ID,
		arg.SiteID,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.BlogID,
		&i.ParentID,
		&i.Type,
		&i.Layout,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
