// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountSites(ctx context.Context) (int64, error)
	CreateBlockCounter(ctx context.Context, siteID int64) (BlockCounter, error)
	CreatePage(ctx context.Context, arg CreatePageParams) (Page, error)
	CreatePageSeo(ctx context.Context, arg CreatePageSeoParams) (CreatePageSeoRow, error)
	CreatePageSlug(ctx context.Context, arg CreatePageSlugParams) (PageSlug, error)
	CreateSectionCounter(ctx context.Context, siteID int64) (SectionCounter, error)
	CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error)
	CreateSiteLocale(ctx context.Context, arg CreateSiteLocaleParams) (SiteLocale, error)
	DeletePage(ctx context.Context, arg DeletePageParams) error
	DeletePageSeoByPageID(ctx context.Context, pageID int64) error
	DeletePageSlugsByPageID(ctx context.Context, pageID int64) error
	DeleteSite(ctx context.Context, id int64) error
	DeleteSiteLocale(ctx context.Context, arg DeleteSiteLocaleParams) error
	DeleteSiteLocaleByCode(ctx context.Context, arg DeleteSiteLocaleByCodeParams) error
	GetBlogByID(ctx context.Context, arg GetBlogByIDParams) (Blog, error)
	GetBlogRoutes(ctx context.Context, siteID int64) ([]GetBlogRoutesRow, error)
	GetNextBlockID(ctx context.Context, siteID int64) (int64, error)
	GetNextSectionID(ctx context.Context, siteID int64) (int64, error)
	GetPageByID(ctx context.Context, arg GetPageByIDParams) (Page, error)
	GetPageRoutes(ctx context.Context, siteID int64) ([]GetPageRoutesRow, error)
	GetPageSeoByPageID(ctx context.Context, pageID int64) ([]GetPageSeoByPageIDRow, error)
	GetPageSeoByPageIDs(ctx context.Context, dollar_1 []int64) ([]GetPageSeoByPageIDsRow, error)
	GetPageSlugsByPageID(ctx context.Context, pageID int64) ([]PageSlug, error)
	GetPageSlugsByPageIDs(ctx context.Context, dollar_1 []int64) ([]PageSlug, error)
	GetPostRoutes(ctx context.Context, siteID int64) ([]GetPostRoutesRow, error)
	GetRootPageBySite(ctx context.Context, siteID int64) (Page, error)
	GetSectionCounter(ctx context.Context, siteID int64) (SectionCounter, error)
	GetSiteByDomain(ctx context.Context, domain string) (Site, error)
	GetSiteByID(ctx context.Context, id int64) (Site, error)
	GetSiteLocaleByCodeAndSite(ctx context.Context, arg GetSiteLocaleByCodeAndSiteParams) (SiteLocale, error)
	GetSiteLocaleByID(ctx context.Context, id int64) (SiteLocale, error)
	ListSiteLocales(ctx context.Context, siteID int64) ([]SiteLocale, error)
	ListSiteLocalesBySiteIDs(ctx context.Context, dollar_1 []int64) ([]SiteLocale, error)
	ListSites(ctx context.Context, arg ListSitesParams) ([]Site, error)
	UnsetDefaultLocales(ctx context.Context, siteID int64) error
	UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error)
	UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error)
}

var _ Querier = (*Queries)(nil)
