// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountSites(ctx context.Context) (int64, error)
	CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error)
	DeleteSite(ctx context.Context, id int64) error
	GetSiteByDomain(ctx context.Context, domain string) (Site, error)
	GetSiteByID(ctx context.Context, id int64) (Site, error)
	ListSites(ctx context.Context, arg ListSitesParams) ([]Site, error)
	UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error)
}

var _ Querier = (*Queries)(nil)
