// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sections.sql

package db

import (
	"context"
)

const createSectionCounter = `-- name: CreateSectionCounter :one
INSERT INTO section_counters (site_id, current_value)
VALUES ($1, 0)
RETURNING site_id, current_value
`

func (q *Queries) CreateSectionCounter(ctx context.Context, siteID int64) (SectionCounter, error) {
	row := q.db.QueryRow(ctx, createSectionCounter, siteID)
	var i SectionCounter
	err := row.Scan(&i.SiteID, &i.CurrentValue)
	return i, err
}

const getNextSectionID = `-- name: GetNextSectionID :one
INSERT INTO section_counters (site_id, current_value)
VALUES ($1, 1)
ON CONFLICT (site_id) DO UPDATE
SET current_value = section_counters.current_value + 1
RETURNING current_value AS id
`

func (q *Queries) GetNextSectionID(ctx context.Context, siteID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getNextSectionID, siteID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getSectionCounter = `-- name: GetSectionCounter :one
SELECT site_id, current_value FROM section_counters WHERE site_id = $1
`

func (q *Queries) GetSectionCounter(ctx context.Context, siteID int64) (SectionCounter, error) {
	row := q.db.QueryRow(ctx, getSectionCounter, siteID)
	var i SectionCounter
	err := row.Scan(&i.SiteID, &i.CurrentValue)
	return i, err
}
