// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sites.sql

package db

import (
	"context"
)

const countSites = `-- name: CountSites :one
SELECT COUNT(*) FROM sites
`

func (q *Queries) CountSites(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSites)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSite = `-- name: CreateSite :one
INSERT INTO sites (name, domain)
VALUES ($1, $2)
RETURNING id, name, domain, created_at, updated_at
`

type CreateSiteParams struct {
	Name   string `json:"name"`
	Domain string `json:"domain"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite, arg.Name, arg.Domain)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSite = `-- name: DeleteSite :exec
DELETE FROM sites WHERE id = $1
`

func (q *Queries) DeleteSite(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSite, id)
	return err
}

const getSiteByDomain = `-- name: GetSiteByDomain :one
SELECT id, name, domain, created_at, updated_at FROM sites WHERE domain = $1
`

func (q *Queries) GetSiteByDomain(ctx context.Context, domain string) (Site, error) {
	row := q.db.QueryRow(ctx, getSiteByDomain, domain)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteByID = `-- name: GetSiteByID :one
SELECT id, name, domain, created_at, updated_at FROM sites WHERE id = $1
`

func (q *Queries) GetSiteByID(ctx context.Context, id int64) (Site, error) {
	row := q.db.QueryRow(ctx, getSiteByID, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSites = `-- name: ListSites :many
SELECT id, name, domain, created_at, updated_at
FROM sites
WHERE ($1::BIGINT IS NULL OR id > $1)
ORDER BY id ASC
LIMIT $2
`

type ListSitesParams struct {
	Column1 int64 `json:"column_1"`
	Limit   int32 `json:"limit"`
}

func (q *Queries) ListSites(ctx context.Context, arg ListSitesParams) ([]Site, error) {
	rows, err := q.db.Query(ctx, listSites, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSite = `-- name: UpdateSite :one
UPDATE sites
SET name = $1, domain = $2, updated_at = NOW()
WHERE id = $3
RETURNING id, name, domain, created_at, updated_at
`

type UpdateSiteParams struct {
	Name   string `json:"name"`
	Domain string `json:"domain"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, updateSite, arg.Name, arg.Domain, arg.ID)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
